mixed-port: 7890
allow-lan: true
log-level: debug
external-controller: '127.0.0.1:56907'
secret: '95217e41-622f-4139-a583-f6a228201004'
ipv6: true

# Will be ignored after profile selection
proxies:
  - name: Shadowsocks
    type: socks5
    server: 127.0.0.1
    port: 1080
proxy-groups:
  - name: Proxy
    type: select
    proxies:
      - Shadowsocks
rules:
  - 'MATCH,DIRECT'
