[Notepad3]
;Notepad3.ini=%USERPROFILE%\Notepad3.ini
;Notepad3.ini=%APPDATA%\Rizonesoft\Notepad3\Notepad3.ini
[Settings]
SettingsVersion=5
WarnInconsistEOLs=false
ShowIndentGuides=true
ViewWhiteSpace=true
ViewEOLs=true
MarkLongLines=true
CloseFind=true
MarkOccurrences=false
WordWrap=false
[Settings2]
;IMEInteraction=0
;DateTimeFormat=          (-> <Locale dependent short format>)
;DateTimeLongFormat=      (-> <Locale dependent long format>)
;TimeStampRegEx=          (-> \$Date:[^\$]+\$ ) (Find-Pattern to Update Stamps)
;TimeStampFormat=         (-> $Date: %s $) {Print format should fit to TimeStampRegEx}
;DefaultDirectory=
;DefaultExtension=txt
;DenyVirtualSpaceAccess=0
filebrowser.exe=minipath.exe
grepWin.exe=grepWinNP3.exe
;FileCheckInverval=0
;FileChangedIndicator=[@]
;FileDeletedIndicator=[X]
;FileDlgFilters=
;FileLoadWarningMB=4
;MultiFileArg=0
;NoCGIGuess=0
;NoCopyLineOnEmptySelection=0
;NoCutLineOnEmptySelection=0
;NoFadeHidden=0
;NoFileVariables=0
;NoHTMLGuess=0
;PortableMyDocs=1
;OpacityLevel=75
;FindReplaceOpacityLevel=50
;RelativeFileMRU=1
;ReuseWindow=0
;SciFontQuality=3
;SimpleIndentGuides=0
;SingleFileInstance=1
;ShellAppUserModelID=Rizonesoft.Notepad3
;ShellUseSystemMRU=1
;StickyWindowPosition=0
;LaunchInstanceWndPosOffset=28
;LaunchInstanceFullVisible=true
;UseOldStyleBraceMatching=0
;WebTemplate1=https://google.com/search?q=%s
;WebTmpl1MenuName=Open Web Action 1
;WebTemplate2=https://en.wikipedia.org/w/index.php?search=%s
;WebTmpl2MenuName=Open Web Action 2
;ExtendedWhiteSpaceChars=
;AutoCompleteWordCharSet=
;AutoCompleteFillUpChars=
;LineCommentPostfixStrg=
;UpdateDelayMarkAllOccurrences=50
;CurrentLineHorizontalSlop=40
;CurrentLineVerticalSlop=5
;UndoTransactionTimeout=0
;AdministrationTool.exe=
;DevDebugMode=0
;AnalyzeReliableConfidenceLevel=75
;LocaleAnsiCodePageAnalysisBonus=33
;LexerSQLNumberSignAsComment=1
;ExitOnESCSkipLevel=2
;ZoomTooltipTimeout=3200
;WrapAroundTooltipTimeout=2000
;LargeIconScalePrecent=150
;DarkModeBkgColor=0x1F1F1F
;DarkModeBtnFaceColor=0x333333
;DarkModeTxtColor=0xEFEFEF
;DarkModeHiglightContrast=75
;HyperlinkShellExURLWithApp=""
;HyperlinkShellExURLCmdLnArgs="${URL}"   (use ${URL} as place holder for clicked Hyperlink URL string)
;HyperlinkFileProtocolVerb=""            (ShellExecuteEx()::lpVerb (""=default, "edit", "explore", "find", "open", "print", "properties", "runas")
[Statusbar Settings]
;VisibleSections=0 1 12 14 2 4 5 6 7 8 9 10 11
;SectionPrefixes=Ln  ,Col  ,Sel  ,Sb  ,SLn  ,Occ  ,,,,,,,Ch  ,Repl  ,Eval  ,
;SectionPostfixes=,,,,,,,,,,,,,,,
;SectionWidthSpecs=30 20 20 20 20 20 0 0 0 0 0 0 20 20 20
;ZeroBasedColumnIndex=0
;ZeroBasedCharacterCount=0
[Toolbar Images]
;BitmapDefault=<[<drive>:|relative_]\path_to>\Toolbar.bmp
;BitmapHot=<[<drive>:|relative_]\path_to>\ToolbarHot.bmp
;BitmapDisabled=<[<drive>:|relative_]\path_to>\ToolbarDisabled.bmp
[Toolbar Labels]
;01=New
;02=Open
;03=Browse
;04=Save
;05=Undo
;06=Redo
;07=Cut
;08=Copy
;09=Paste
;10=Find
;11=Replace
;12=Word Wrap
;13=Zoom In
;14=Zoom Out
;15=Scheme
;16=Customize Schemes
;17=Exit
;18=Save As
;19=Save Copy
;20=Delete
;21=Print
;22=Favorites
;23=Add to Favorites
;24=Toggle Folds
;25=Execute Document
;26=Focused View
;27=Monitoring Log
;28=History
;29=Always On Top
;30=Search in Files
[Styles]
[Window]
2560x1440 HighDpiToolBar=0
2560x1440 PosX=802
2560x1440 PosY=94
2560x1440 SizeX=1632
2560x1440 SizeY=1265
2560x1440 Maximized=false
2560x1440 Zoom=100
2560x1440 DPI=120
;<ResX>x<ResY> DefaultWindowPosition=
[Suppressed Messages]
MsgFileUnknownExt=6
[Custom Colors]
[Common Base]
Default Style=font:ConsolasLXGWWenKaiNFM; size:12; charset:134
[2nd Common Base]
[Text Files]
[ANSI Art]
Default=font:CaskaydiaMono NFP; size:12; smoothing:aliased
[Apache Config Files]
[Assembly Script]
[AutoHotkey Script]
[AutoIt3 Script]
[AviSynth Script]
[Awk Script]
[Batch Files]
[C# Source Code]
[C/C++ Source Code]
[Cmake Script]
[Coffeescript]
[Configuration Files]
[CSS Style Sheets]
[CSV Prism]
[D Source Code]
[Dart Source Code]
[Diff Files]
[Fortran Source Code]
[Go Source Code]
[Inno Setup Script]
[Java Source Code]
[JavaScript]
[JSON]
[Julia Script]
[KiXtart Script]
[Kotlin Source Code]
[LaTeX Files]
[Lua Script]
[Makefiles]
[Markdown]
[MATLAB]
[Nim Source Code]
[NSIS Script]
[Pascal Source Code]
[Perl Script]
[PowerShell Script]
[Python Script]
[Registry Files]
[Resource Script]
[R-S-SPlus Statistics Code]
[Ruby Script]
[Rust Source Code]
[Shell Script]
Default=font:ConsolasLXGWWenKaiNFM; size:12; charset:134
[SQL Query]
[Tcl Script]
[TOML Config]
[VBScript]
[VHDL]
[Visual Basic]
[Web Source Code]
[XML Document]
[YAML]
[Recent Files]
01="%USERPROFILE%\scoop\persist\notepad3-pre\minipath.ini"
ENC01=4
02="%USERPROFILE%\scoop\persist\notepad3-pre\Notepad3.ini"
ENC02=4
03="%USERPROFILE%\scoop\persist\localsend\settings.json"
ENC03=3
04="%USERPROFILE%\scoop\persist\gui-for-clash\data\user.yaml"
ENC04=3
05="%USERPROFILE%\scoop\persist\goldendict-ng\portable\config"
ENC05=3
06="%USERPROFILE%\source\Exported-2024-06-26.vssettings"
ENC06=3
07="%USERPROFILE%\.whim\whim.config.csx"
ENC07=3
08="%USERPROFILE%\.whim\whim.config.yaml"
ENC08=3
09="%USERPROFILE%\.cache\LeaderF\gtags\_wildignore.options"
ENC09=3
10="%USERPROFILE%\.cache\pnpm\global\5\package.json"
ENC10=3
11="%USERPROFILE%\.cache\vim\coc\extensions\package.json"
ENC11=3
12="%USERPROFILE%\.cache\vim\coc\memos.json"
ENC12=3
13="%USERPROFILE%\.cache\clib\search.html"
ENC13=3
14="%USERPROFILE%\.config\clash\cfw-settings.yaml"
ENC14=3
15="%USERPROFILE%\.config\clash\config.yaml"
ENC15=3
16="%USERPROFILE%\.config\mihomo-tui\config.yaml"
ENC16=3
17="%USERPROFILE%\.config\yazi-alt\package.toml"
ENC17=3
18="%USERPROFILE%\.config\yazi-alt\yazi.toml"
ENC18=3
19="%USERPROFILE%\.config\wezterm\config\keys.lua"
ENC19=3
20="%USERPROFILE%\.config\efm-langserver\config.yaml.bak"
ENC20=3
21="%USERPROFILE%\.config\configstore\update-notifier-npm-check-updates.json"
ENC21=3
22="%USERPROFILE%\.config\clash\logs\2026-04-25-194048.log"
ENC22=3
23="%USERPROFILE%\.config\clash\logs\2026-04-22-074639.log"
ENC23=3
24="%USERPROFILE%\.config\starship.toml"
ENC24=3
25="%USERPROFILE%\.config\atuin\config.toml"
ENC25=3
26="%USERPROFILE%\.config\clash\providers\proxy\1f069d32bdcf364290f0f51c5c881849.yaml"
ENC26=3
27="%USERPROFILE%\.config\clash\providers\proxy\43bf5f6c19a982c80cfb3ab3d9e98f40.yaml"
ENC27=3
28="%USERPROFILE%\scoop\persist\v2rayn-pre\guiConfigs\guiNConfig.json"
ENC28=3
29="%USERPROFILE%\scoop\persist\texstudio-cn\config\cache\tikz_datavisualization.json"
ENC29=3
30="%USERPROFILE%\scoop\persist\texstudio-cn\config\texstudio.ini"
ENC30=3
31="%USERPROFILE%\scoop\persist\smartdns-rs\smartdns.conf"
ENC31=3
32="%USERPROFILE%\scoop\persist\nilesoft-shell\shell.nss"
ENC32=4
[Recent Find]
[Recent Replace]
